#!/bin/bash

file_name="$1"

# output=$(sqlfluff parse --dialect postgres "$file_name")
# if [[ $? -eq 1 ]]; then
#   errors=$(echo "$output" | awk '/==== parsing violations ====/ {p=1; next} p{print}')
#   # append filename to each error line
#   while IFS= read -r line; do
#     if [[ $line == L:* ]]; then
#       echo "$file_name: $line"
#     fi
#   done <<< "$errors"
# fi

export PGPASSWORD="ryan"

# select 'MARKER' as marker union all
# output=$(echo "$psql_output" | awk '/MARKER/ {p=1; next} p{print}')

PGOPTIONS='--client-min-messages=warning' psql -U ryan -h localhost -d quiz -q -f "$file_name"

# Test schema
# db="ass1"
# dropdb "$db"
# createdb "$db"
# psql "$db" -f schema.sql > .errs 2>&1
# grep ERR log 
# continue until log error free

# 3311 autotest ass1 Q4 
