#!/bin/bash

file_name="$1"

#python3 "$file_name" 

# src/servt -x -o (moves 'x' and 'o' made by us)
# src/servt -p 12345 -x (wait for 'o' connection)

# src/randt -p 12345
# python3 src/agent.py -p 12345
# src/lookt -p 12345

num_clients=3
num_cols=1

GLOBAL_DESKTOP_ENVIRONMENT_SCALE=2

window_size_str=$(xrandr | grep '*')
prev_ifs=$IFS
IFS=' '
set -- $window_size_str
IFS=$prev_ifs
window_size_str=$1
window_width=${window_size_str%x*}
window_height=${window_size_str#*x}
let window_width/=GLOBAL_DESKTOP_ENVIRONMENT_SCALE
let window_height/=GLOBAL_DESKTOP_ENVIRONMENT_SCALE

num_rows=$(( (num_clients+num_cols-1)/num_cols ))
client_width=$(( window_width/num_cols ))
client_height=$(( window_height/num_rows ))

clients=( "servt" "ass3.py" "lookt" )

client_i=0
client_y_offset=0
for (( y=0; y<num_rows; y++ )) 
do
  client_x_offset=0
  for (( x=0; x<num_cols; x++ )) 
  do
    client_geometry="${client_width}x${client_height}+${client_x_offset}+${client_y_offset}"
    # IMPORTANT(Ryan): To persist after execution append "&& bash || bash"
    terminator --title="client${client_i}" --geometry="$client_geometry" -x bash "${clients[$client_i]} -p 54321"
    # IMPORTANT(Ryan): Faster launching acheived by appended &, however then don't stack on top in order
    let client_x_offset+=client_width
    let client_i+=1
  done
  let client_y_offset+=client_height
done




#start=$(date +%s.%N)
#
#
#end=$(date +%s.%N)
#total_time=$( echo "scale=4; ($end - $start)" | bc -l )
#printf "Total Time: %.4fs\n" "$total_time" 
