LIBRARY ieee ;
USE ieee.std_logic_1164.all ;
ENTITY lab01 IS
PORT ( sw: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
ledg : OUT STD_LOGIC_VECTOR(9 DOWNTO 0)) ;
END lab01 ;

ARCHITECTURE LogicFunction OF lab01 IS
BEGIN
ledg(0) <= (sw(0) AND NOT sw(1)) OR (NOT sw(0) AND sw(1));
END LogicFunction ;

-- quartus templates
-- import .qsf assignment file
-- outside editor files manually added
-- entity must be same name as file?
-- select above line in .vwf file
-- program .sof (SRAM Object File) (.pof file also generated by compiler)
-- .cdf (chain description file) for programmer options