#!/bin/python

def est(est_rtt, sample_rtt):
  return ((1 - 0.125)*(est_rtt)) + (0.125 * sample_rtt)

est_rtt = est(0.027460, 0.027460)
print(est_rtt)
est_rtt = est(est_rtt, 0.035557)
print(est_rtt)
est_rtt = est(est_rtt, 0.070059)
print(est_rtt)
est_rtt = est(est_rtt, 0.114428)
print(est_rtt)
est_rtt = est(est_rtt, 0.139894)
print(est_rtt)
est_rtt = est(est_rtt, 0.189645)
print(est_rtt)
