#!/bin/bash

file_name="$1"

# python3 "$file_name" 

# verify
rows=10
cols=10
./bridgen $rows $cols > hashi.puzzle
python3 "$file_name" < hashi.puzzle > hashi.puzzle.solution

debug=0
if [[ $debug -eq 1 ]]; then
  cat hashi.puzzle.solution
else
  ./bridgecheck hashi.puzzle < hashi.puzzle.solution
fi
