#!/bin/bash

file_name="$1"

# python3 "$file_name" 

start=$(date +%s.%N)

# verify
rows=21
cols=21
./bridgen $rows $cols > hashi.puzzle
python3 "$file_name" < hashi.puzzle > hashi.puzzle.solution
./bridgecheck hashi.puzzle < hashi.puzzle.solution
#python3 "$file_name" < hashi.puzzle

# debug=0
# if [[ $debug -eq 1 ]]; then
#   cat hashi.puzzle.solution
# else
#   ./bridgecheck hashi.puzzle < hashi.puzzle.solution
# fi

end=$(date +%s.%N)
total_time=$( echo "scale=4; ($end - $start)" | bc -l )
printf "Total Time: %.4fs\n" "$total_time" 
