#!/bin/bash

set -e

mkdir -p build

input_tex='mcu.tex'
output_pdf="${input_md%%.tex}.pdf"

# pdflatex mcu.tex

# NOTE(Ryan): These variables are what could appear in a latex yaml header
# NOTE(Ryan): Possible font sizes are 8pt, 9pt, 10pt, 11pt, 12pt, 14pt, 17pt, 20pt
pandoc -V documentclass=extarticle -V fontsize=20pt -V pagestyle=empty \
  -V geometry:margin=1cm \
  src/"$input_md" --pdf-engine=xelatex -o build/"$output_pdf"

pdftoppm -jpeg -r 300 build/"$output_pdf" photos/"$output_jpeg"

# xdg-open "$file".jpeg-1.jpg
