#!/bin/bash

# TODO(Ryan): Might have to convert to Makefile...
set -e

mkdir -p build

gcc -g -DDEBUG -DAUTOMATE code/server.c -o build/server -lm
 
gcc -fsanitize=address -g -DDEBUG -DAUTOMATE code/client.c -o build/client -lm

# gcc -g code/stackoverflow.c -o build/stackoverflow
