@startuml
hide circle
skinparam linetype ortho

entity "Entity01" as e01 {
  * primary_foreign_key: number
  --
  some_val: text
}

entity "Entity02" as e02 {
  * primary_foreign_key: number
  --
  some_val: text
}

' Zero or One    |o--
' Exactly One    ||--
' Zero or Many   }o--
' One or Many    }|--

e01 |o-- e02


@enduml
