#!/bin/bash

file_name="$1"

#python3 "$file_name" 

# src/servt -x -o (moves 'x' and 'o' made by us)
# src/servt -p 12345 -x (wait for 'o' connection)

# src/randt -p 12345
# python3 src/agent.py -p 12345
# src/lookt -p 12345

start=$(date +%s.%N)


end=$(date +%s.%N)
total_time=$( echo "scale=4; ($end - $start)" | bc -l )
printf "Total Time: %.4fs\n" "$total_time" 
